const REEMPLAZOS: ReadonlyArray<readonly [RegExp, string]> = [
  [/\b(kipping muscle[- ]?up)\b/gi, 'subida dinámica a la barra'],
  [/\b(weighted muscle[- ]?up)\b/gi, 'subida a la barra lastrada'],
  [/\b(cable standing up straight crossovers)\b/gi, 'cruces rectos de pie en polea'],
  [/\b(cable twist \(up-down\))\b/gi, 'giro arriba-abajo en polea'],
  [/\b(body saw)\b/gi, 'sierra corporal'],
  [/\b(back and forth)\b/gi, 'adelante y atrás'],
  [/\b(battling ropes?)\b/gi, 'cuerdas de batalla'],
  [/\b(dead bug)\b/gi, 'insecto muerto'],
  [/\b(exercise ball)\b/gi, 'balón de ejercicio'],
  [/\b(jackknife)\b/gi, 'navaja abdominal'],
  [/\b(mountain climbers?)\b/gi, 'escaladores'],
  [/\b(skull ?crusher)\b/gi, 'rompecráneos'],
  [/\b(one leg)\b/gi, 'a una pierna'],
  [/\b(two legs)\b/gi, 'a dos piernas'],
  [/\b(bodyweight)\b/gi, 'peso corporal'],
  [/\b(body weight)\b/gi, 'peso corporal'],
  [/\b(reps?)\b/gi, 'repeticiones'],
  [/\b(pull[- ]?ups?)\b/gi, 'dominadas'],
  [/\b(chin[- ]?ups?)\b/gi, 'dominadas supinas'],
  [/\b(cross[- ]?body)\b/gi, 'cruzado'],
  [/\b(cross[- ]?overs?|crossover)\b/gi, 'cruces'],
  [/\bup-down\b/gi, 'arriba-abajo'],
  [/\b(legs? up)\b/gi, 'pierna elevada'],
  [/\b(otis up)\b/gi, 'abdominal Otis'],
  [/\b(body-up)\b/gi, 'elevación de cuerpo'],
  [/\b(curl-up)\b/gi, 'abdominal curl'],
  [/\b(world greatest stretch)\b/gi, 'el mejor estiramiento del mundo'],
  [/\b(cross trainer)\b/gi, 'máquina elíptica'],
  [/\b(balance board)\b/gi, 'tabla de equilibrio'],
  [/\b(balance)\b/gi, 'equilibrio'],
  [/\b(around world)\b/gi, 'alrededor del mundo'],
  [/\b(v[- ]?up)\b/gi, 'abdominal en V'],
  [/\b(muscle[- ]?up)\b/gi, 'subida a la barra'],
  [/\b(get up)\b/gi, 'levantamiento turco'],
  [/\b(bottoms[- ]?up)\b/gi, 'de abajo arriba'],
  [/\b(palms? up)\b/gi, 'palmas hacia arriba'],
  [/\b(sissy squat)\b/gi, 'sentadilla sissy'],
  [/\b(round arm)\b/gi, 'brazo circular'],
  [/\b(zottman preacher curl)\b/gi, 'curl predicador Zottman'],
  [/\b(zottman curl)\b/gi, 'curl Zottman'],
  [/\b(all fours)\b/gi, 'en cuadrupedia'],
  [/\b(air bike)\b/gi, 'bicicleta de aire'],
  [/\b(jumping jacks?)\b/gi, 'saltos de tijera'],
  [/\b(bicycle crunch)\b/gi, 'abdominal bicicleta'],
  [/\b(russian twist)\b/gi, 'giro ruso'],
  [/\b(jack knife)\b/gi, 'navaja abdominal'],
  [/\b(wheel rollerout|rollerout|wheel rollout)\b/gi, 'despliegue con rueda abdominal'],
  [/\b(heel touchers?)\b/gi, 'toques de talón'],
  [/\b(toe touch)\b/gi, 'toque de pies'],
  [/\b(sit[- ]?up)\b/gi, 'abdominal'],
  [/\b(side bend)\b/gi, 'inclinación lateral'],
  [/\b(chin[- ]?up)\b/gi, 'dominada supina'],
  [/\b(pull[- ]?up)\b/gi, 'dominada'],
  [/\b(push[- ]?up)\b/gi, 'flexión'],
  [/\b(dips?|dip)\b/gi, 'fondos'],
  [/\b(bench press)\b/gi, 'press de banca'],
  [/\b(chest press)\b/gi, 'press de pecho'],
  [/\b(shoulder press)\b/gi, 'press de hombros'],
  [/\b(military press)\b/gi, 'press militar'],
  [/\b(overhead press)\b/gi, 'press por encima de la cabeza'],
  [/\b(stiff leg deadlift)\b/gi, 'peso muerto con piernas rígidas'],
  [/\b(straight leg deadlift)\b/gi, 'peso muerto con piernas extendidas'],
  [/\b(deadlift)\b/gi, 'peso muerto'],
  [/\b(split squat)\b/gi, 'sentadilla dividida'],
  [/\b(front squat)\b/gi, 'sentadilla frontal'],
  [/\b(hack squat)\b/gi, 'sentadilla hack'],
  [/\b(squat)\b/gi, 'sentadilla'],
  [/\b(step[- ]?up)\b/gi, 'subida al banco'],
  [/\b(lunge)\b/gi, 'zancada'],
  [/\b(hip thrust)\b/gi, 'empuje de cadera'],
  [/\b(clean and press)\b/gi, 'cargada y press'],
  [/\b(clean)\b/gi, 'cargada'],
  [/\b(snatch)\b/gi, 'arranque'],
  [/\b(jerk)\b/gi, 'envión'],
  [/\b(farmer(?:s)?)\b/gi, 'paseo del granjero'],
  [/\b(good morning)\b/gi, 'buenos días'],
  [/\b(pallof press)\b/gi, 'press Pallof'],
  [/\b(pulldown)\b/gi, 'jalón'],
  [/\b(pushdown)\b/gi, 'extensión en polea'],
  [/\b(pullover)\b/gi, 'pull-over'],
  [/\b(pull through)\b/gi, 'tirón de cadera'],
  [/\b(row)\b/gi, 'remo'],
  [/\b(curls?)\b/gi, 'flexión'],
  [/\b(lever)\b/gi, 'palanca'],
  [/\b(ball)\b/gi, 'balón'],
  [/\b(preacher)\b/gi, 'predicador'],
  [/\b(hammer)\b/gi, 'martillo'],
  [/\b(rope)\b/gi, 'cuerda'],
  [/\b(pulley)\b/gi, 'polea'],
  [/\b(sled|sledge)\b/gi, 'trineo'],
  [/\b(kettlebell)\b/gi, 'pesa rusa'],
  [/\b(press(?:es)?)\b/gi, 'empuje'],
  [/\b(raise|raises)\b/gi, 'elevación'],
  [/\b(extension|extensions)\b/gi, 'extensión'],
  [/\b(flyes?)\b/gi, 'aperturas'],
  [/\b(narrow)\b/gi, 'estrecho'],
  [/\b(stance)\b/gi, 'postura'],
  [/\b(high)\b/gi, 'alto'],
  [/\b(low)\b/gi, 'bajo'],
  [/\b(bent)\b/gi, 'flexionado'],
  [/\b(straight)\b/gi, 'recto'],
  [/\b(delt|deltoid)\b/gi, 'deltoides'],
  [/\b(internal)\b/gi, 'interna'],
  [/\b(external)\b/gi, 'externa'],
  [/\b(stirrups?)\b/gi, 'estribos'],
  [/\b(attachment)\b/gi, 'accesorio'],
  [/\b(stability)\b/gi, 'estabilidad'],
  [/\b(inverse)\b/gi, 'inverso'],
  [/\b(supinated)\b/gi, 'supinado'],
  [/\b(supination)\b/gi, 'supinación'],
  [/\b(pronated)\b/gi, 'pronado'],
  [/\b(pronation)\b/gi, 'pronación'],
  [/\b(extended)\b/gi, 'extendido'],
  [/\b(range)\b/gi, 'rango'],
  [/\b(above)\b/gi, 'encima'],
  [/\b(over)\b/gi, 'sobre'],
  [/\b(head)\b/gi, 'cabeza'],
  [/\b(skull)\b/gi, 'cráneo'],
  [/\b(drag)\b/gi, 'arrastre'],
  [/\b(lift)\b/gi, 'elevación'],
  [/\b(russian)\b/gi, 'ruso'],
  [/\b(twists?)\b/gi, 'giros'],
  [/\b(twisting)\b/gi, 'con giro'],
  [/\b(variation)\b/gi, 'variante'],
  [/\b(support(?:ed)?)\b/gi, 'apoyo'],
  [/\b(finger|fingers)\b/gi, 'dedo'],
  [/\b(row_shoulder)\b/gi, 'remo de hombros'],
  [/\b(butt[- ]?ups?)\b/gi, 'elevaciones de glúteos'],
  [/\b(up)\b/gi, 'arriba'],
  [/\b(upright)\b/gi, 'vertical'],
  [/\b(sternum)\b/gi, 'esternón'],
  [/\b(chin)\b/gi, 'barbilla'],
  [/\b(pirate)\b/gi, 'pirata'],
  [/\b(supper)\b/gi, 'super'],
  [/\b(mixed)\b/gi, 'mixto'],
  [/\b(oblique)\b/gi, 'oblicuo'],
  [/\b(crunches)\b/gi, 'abdominales'],
  [/\b(lower)\b/gi, 'inferior'],
  [/\b(upper)\b/gi, 'superior'],
  [/\b(neck)\b/gi, 'cuello'],
  [/\b(between)\b/gi, 'entre'],
  [/\b(benches?)\b/gi, 'bancos'],
  [/\b(butt[- ]?ups?)\b/gi, 'elevaciones de glúteos'],
  [/\b(dynamic)\b/gi, 'dinámico'],
  [/\b(drop)\b/gi, 'caída'],
  [/\b(ups?)\b/gi, 'elevaciones'],
  [/\b(pyramid)\b/gi, 'pirámide'],
  [/\b(upward)\b/gi, 'ascendente'],
  [/\b(facing)\b/gi, 'mirando'],
  [/\b(dog)\b/gi, 'perro'],
  [/\b(toes?)\b/gi, 'dedo del pie'],
  [/\b(raised)\b/gi, 'elevado'],
  [/\b(legged)\b/gi, 'con piernas'],
  [/\b(modified)\b/gi, 'modificado'],
  [/\b(backward)\b/gi, 'hacia atrás'],
  [/\b(butterfly)\b/gi, 'mariposa'],
  [/\b(pose)\b/gi, 'postura'],
  [/\b(squad)\b/gi, 'cuclillas'],
  [/\b(big)\b/gi, 'grande'],
  [/\b(squatting)\b/gi, 'en sentadilla'],
  [/\b(kickbacks?)\b/gi, 'patadas hacia atrás'],
  [/\b(dumbbells?)\b/gi, 'mancuernas'],
  [/\b(sitted)\b/gi, 'sentado'],
  [/\b(stepbox)\b/gi, 'cajón'],
  [/\b(cage)\b/gi, 'jaula'],
  [/\b(scissor)\b/gi, 'tijera'],
  [/\b(jumps?)\b/gi, 'saltos'],
  [/\b(astride)\b/gi, 'a horcajadas'],
  [/\b(wheel)\b/gi, 'rueda'],
  [/\b(outstretched)\b/gi, 'extendida'],
  [/\b(ski)\b/gi, 'esquí'],
  [/\b(step)\b/gi, 'paso'],
  [/\b(body)\b/gi, 'cuerpo'],
  [/\b(roller)\b/gi, 'rodillo'],
  [/\b(saw)\b/gi, 'sierra'],
  [/\b(extension)\b/gi, 'extensión'],
  [/\b(raise)\b/gi, 'elevación'],
  [/\b(fly)\b/gi, 'apertura'],
  [/\b(shrug)\b/gi, 'encogimiento de hombros'],
  [/\b(crunch)\b/gi, 'encogimiento abdominal'],
  [/\b(plank)\b/gi, 'plancha'],
  [/\b(twist)\b/gi, 'giro'],
  [/\b(rotation)\b/gi, 'rotación'],
  [/\b(kickback)\b/gi, 'patada hacia atrás'],
  [/\b(bridge)\b/gi, 'puente'],
  [/\b(fallout)\b/gi, 'despliegue'],
  [/\b(stretch)\b/gi, 'estiramiento'],
  [/\b(circle)\b/gi, 'círculo'],
  [/\b(swing)\b/gi, 'balanceo'],
  [/\b(walkout)\b/gi, 'caminata hacia adelante'],
  [/\b(walk)\b/gi, 'caminata'],
  [/\b(run)\b/gi, 'carrera'],
  [/\b(jump)\b/gi, 'salto'],
  [/\b(throw down)\b/gi, 'lanzamiento hacia abajo'],
  [/\b(throw)\b/gi, 'lanzamiento'],
  [/\b(down)\b/gi, 'abajo'],
  [/\b(touch)\b/gi, 'toque'],
  [/\b(barbell)\b/gi, 'barra'],
  [/\b(olympic bar)\b/gi, 'barra olímpica'],
  [/\b(ez bar)\b/gi, 'barra EZ'],
  [/\b(dumbbell)\b/gi, 'mancuerna'],
  [/\b(resistance band)\b/gi, 'banda elástica'],
  [/\b(band)\b/gi, 'banda elástica'],
  [/\b(cable)\b/gi, 'polea'],
  [/\b(smith machine)\b/gi, 'máquina Smith'],
  [/\b(machine)\b/gi, 'máquina'],
  [/\b(medicine ball)\b/gi, 'balón medicinal'],
  [/\b(stability ball)\b/gi, 'balón de estabilidad'],
  [/\b(body[- ]?weight)\b/gi, 'peso corporal'],
  [/\b(weighted)\b/gi, 'lastrado'],
  [/\b(assisted)\b/gi, 'asistido'],
  [/\b(seated)\b/gi, 'sentado'],
  [/\b(standing)\b/gi, 'de pie'],
  [/\b(lying)\b/gi, 'acostado'],
  [/\b(prone)\b/gi, 'boca abajo'],
  [/\b(supine)\b/gi, 'boca arriba'],
  [/\b(kneeling)\b/gi, 'de rodillas'],
  [/\b(hanging)\b/gi, 'colgado'],
  [/\b(incline)\b/gi, 'inclinado'],
  [/\b(decline)\b/gi, 'declinado'],
  [/\b(reverse)\b/gi, 'inverso'],
  [/\b(alternating|alternate)\b/gi, 'alterno'],
  [/\b(single leg)\b/gi, 'a una pierna'],
  [/\b(one arm)\b/gi, 'a un brazo'],
  [/\b(two legs)\b/gi, 'a dos piernas'],
  [/\b(close[- ]grip)\b/gi, 'agarre cerrado'],
  [/\b(wide[- ]grip)\b/gi, 'agarre amplio'],
  [/\b(front)\b/gi, 'frontal'],
  [/\b(rear)\b/gi, 'posterior'],
  [/\b(lateral|side)\b/gi, 'lateral'],
  [/\b(bent[- ]over)\b/gi, 'inclinado'],
  [/\b(straight leg)\b/gi, 'pierna extendida'],
  [/\b(parallel)\b/gi, 'paralelo'],
  [/\b(behind)\b/gi, 'detrás'],
  [/\b(full)\b/gi, 'completo'],
  [/\b(against)\b/gi, 'contra'],
  [/\b(underhand)\b/gi, 'agarre supino'],
  [/\b(overhand)\b/gi, 'agarre prono'],
  [/\b(neutral)\b/gi, 'neutro'],
  [/\b(suspended)\b/gi, 'suspendido'],
  [/\b(inverted)\b/gi, 'invertido'],
  [/\b(wall)\b/gi, 'pared'],
  [/\b(floor)\b/gi, 'suelo'],
  [/\b(plate|disc)\b/gi, 'disco'],
  [/\b(towel)\b/gi, 'toalla'],
  [/\b(chair)\b/gi, 'silla'],
  [/\b(bench)\b/gi, 'banco'],
  [/\b(box)\b/gi, 'cajón'],
  [/\b(pull)\b/gi, 'tirón'],
  [/\b(push)\b/gi, 'empuje'],
  [/\b(knee|knees)\b/gi, 'rodilla'],
  [/\b(arm|arms)\b/gi, 'brazo'],
  [/\b(chest)\b/gi, 'pecho'],
  [/\b(back)\b/gi, 'espalda'],
  [/\b(shoulder)\b/gi, 'hombro'],
  [/\b(leg|legs)\b/gi, 'pierna'],
  [/\b(calf)\b/gi, 'pantorrilla'],
  [/\b(calves)\b/gi, 'pantorrillas'],
  [/\b(hip|hips)\b/gi, 'cadera'],
  [/\b(glutes?|gluteus)\b/gi, 'glúteo'],
  [/\b(hamstring)\b/gi, 'isquiotibial'],
  [/\b(quads?)\b/gi, 'cuádriceps'],
  [/\b(triceps?|tricep)\b/gi, 'tríceps'],
  [/\b(biceps?|bicep)\b/gi, 'bíceps'],
  [/\b(wrist)\b/gi, 'muñeca'],
  [/\b(without)\b/gi, 'sin'],
  [/\b(with)\b/gi, 'con'],
  [/\b(and)\b/gi, 'y'],
  [/\b(on|in)\b/gi, 'en'],
  [/\b(to)\b/gi, 'a'],
  [/\b(for)\b/gi, 'para'],
  [/\b(of)\b/gi, 'de'],
  [/\b(the)\b/gi, ''],
  [/\b(male|female)\b/gi, ''],
  [/\b(exercise)\b/gi, 'ejercicio'],
  [/\b(rectus femoris)\b/gi, 'recto femoral'],
  [/\b(piriformis)\b/gi, 'piriforme'],
  [/\b(adductor)\b/gi, 'aductor'],
  [/\b(pectoralis major)\b/gi, 'pectoral mayor'],
  [/\b(motion)\b/gi, 'movimiento'],
  [/\b(straddle)\b/gi, 'a horcajadas'],
  [/\b(swimmer)\b/gi, 'nadador'],
  [/\b(tire)\b/gi, 'neumático'],
  [/\b(trap bar)\b/gi, 'barra hexagonal'],
  [/\b(slingers?|slings?)\b/gi, 'lanzamientos'],
  [/\b(fixed)\b/gi, 'fijo'],
  [/\b(cossack)\b/gi, 'cosaco'],
  [/\b(sissy)\b/gi, 'de cuádriceps'],
  [/\b(squats?)\b/gi, 'sentadillas'],
  [/\b(maltese)\b/gi, 'maltés'],
  [/\b(wind sprints?)\b/gi, 'sprints de viento'],
  [/\b(overhead)\b/gi, 'por encima de la cabeza'],
  [/\b(pectoral)\b/gi, 'pectoral'],
  [/\b(pec)\b/gi, 'pectoral'],
  [/\b(treadmill)\b/gi, 'cinta de correr'],
  [/\b(elliptical)\b/gi, 'elíptica'],
  [/\b(stepmill)\b/gi, 'escaladora'],
  [/\b(vertical)\b/gi, 'vertical'],
  [/\b(horizontal)\b/gi, 'horizontal'],
  [/\b(crossovers?)\b/gi, 'cruces'],
  [/\b(position)\b/gi, 'posición'],
  [/\b(style)\b/gi, 'estilo'],
  [/\b(from)\b/gi, 'desde'],
  [/\b(pov)\b/gi, 'POV'],
  [/\b(zt?ottman)\b/gi, 'Zottman'],
  [/\b(two)\b/gi, 'dos'],
  [/\b(one)\b/gi, 'uno'],
  [/\b(three)\b/gi, 'tres'],
  [/\b(v)\b/gi, 'V'],
  [/\b(bar)\b/gi, 'barra'],
  [/\b(grip)\b/gi, 'agarre'],
];

function limpiar(texto: string) {
  return texto
    .replace(/\s+/g, ' ')
    .replace(/\(\s*\)/g, '')
    .replace(/\s+([,)])/g, '$1')
    .replace(/([,(])\s+/g, '$1 ')
    .replace(/\s+-\s*/g, ' - ')
    .trim();
}

function normalizarNombreCanonico(texto: string) {
  return texto
    .replace(/\blastrado\s+(sentadilla|zancada|prensa|extensi[oó]n)\b/gi, '$1 lastrada')
    .replace(/\blastrado\s+(curl)\b/gi, '$1 lastrado')
    .replace(/\bpress\s+banca\b/gi, 'press de banca')
    .replace(/\bdominadas\s+agarre\b/gi, 'dominadas con agarre');
}

export function traducirNombreEjercicio(nombre: string) {
  let resultado = nombre.replace(/\s*\((male|female)\)\s*/gi, ' ').replace(/\s+/g, ' ').trim();
  for (const [patron, reemplazo] of REEMPLAZOS) resultado = resultado.replace(patron, reemplazo);
  resultado = normalizarNombreCanonico(limpiar(resultado));
  return resultado ? `${resultado[0].toLocaleUpperCase('es-CO')}${resultado.slice(1)}` : 'Ejercicio';
}
